CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS_2ANO;
USE BD_ALUGUEL_PRODUTOS_2ANO;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULAÇÃO 
-- INSERT  - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME) 
VALUES ("email@email.com","19999999999","123456789","Leo");

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME) 
VALUES ("vinicius.lima23vi13ni@gmail.com","19991925125","52392452822","Vini");

INSERT INTO CLIENTE(NOME,EMAIL,TELEFONE,CPF)
VALUES("Alison","alison@email.com","19998982343","12334565321");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;