CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA_2ANO;
USE BD_APLICATIVO_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FOTO BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	NOME VARCHAR(255) PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    CAPA BLOB NOT NULL,
    QTD_FAIXA INTEGER NOT NULL,
    DURACAO VARCHAR(5) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_CPF_ARTISTA VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    LETRA VARCHAR(1000),
    DURACAO VARCHAR(5) NOT NULL,
    FOTO_CAPA BLOB NOT NULL,
    FK_ID_ALBUM INTEGER NOT NULL,
    FK_NOME_GENERO VARCHAR(255) NOT NULL,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_NOME_GENERO) REFERENCES GENERO(NOME) ON DELETE CASCADE
);