CREATE DATABASE BD_CONSULTA_MEDICA;
USE BD_CONSULTA_MEDICA;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PLANO VARCHAR(255) NOT NULL,
    CADASTRO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(12) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SENHA VARCHAR(10) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    DATA_CONSULTA DATE NOT NULL,
    FK_CPF_PACIENTE VARCHAR(15) NOT NULL,
    FK_CRM_MEDICO VARCHAR(12) NOT NULL,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE
);