CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE_2ANO;
USE BD_GESTAO_ESTOQUE_2ANO;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    VALIDADE DATE,
    QTD_PRODUTO INTEGER NOT NULL,
    FOTO BLOB NOT NULL,
    PESO VARCHAR(10) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR(14) NOT NULL,
    FK_ID_PRODUTO INTEGER NOT NULL,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);