CREATE DATABASE BD_GERENCIAR_PROJETOS_2ANO;
USE BD_GERENCIAR_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    SETOR VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    ORCAMENTO DOUBLE NOT NULL	
);	

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    TEMPO_ESTIMADO VARCHAR (10) NOT NULL,
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS POSSUIR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_TAREFA INTEGER NOT NULL,
    FK_CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_TAREFA) REFERENCES TAREFA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);