CREATE DATABASE BD_GEREN_BIBLIO_DIG;
USE BD_GEREN_BIBLIO_DIG;

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    GENERO_ATUANTE VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_CPF_LEITOR VARCHAR(15) NOT NULL,
    FK_CPF_AUTOR VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);