CREATE DATABASE BD_STREAM_VIDEO_2ANO;
USE BD_STREAM_VIDEO_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TEMPO VARCHAR(6) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
    
);

CREATE TABLE IF NOT EXISTS VIZUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(50) NOT NULL,
    QTD_VIZUALIZACAO VARCHAR(255) NOT NULL,
    FK_ID_VIDEO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID) ON DELETE CASCADE
);